version: '2'
services:
  sdl_core:
    image: 'sdl_core:latest'
    ports:
      - "3001:3001"
      - "8087:8087"
      - "8090:8090"
      - "12345:12345"

  sdl_hmi:
    image: 'generic_hmi:latest'
    ports:
      - '3000:3000'
      - '8088:8088'
      - '8089:8089'
      - '8081:8081'
      - '2468:2468'
