version: '2'
services:
  sdl_core:
    image: 'sdl_core:latest'
    ports:
      - "3001:3001"
      - "8087:8087"
      - "8090:8090"
      - "12345:12345"

  generic_hmi:
    image: 'generic_hmi:latest'
    ports:
      - '3000:80'
